
figure
subplot(3,3,1)
plot(time,WG1,'.-b')
subplot(3,3,2)
plot(time,WG2,'.-b')
subplot(3,3,3)
plot(time,WG3,'.-b')
subplot(3,3,4)
plot(time,WG4,'.-b')
subplot(3,3,5)
plot(time,WG5,'.-b')
subplot(3,3,6)
plot(time,WG6,'.-b')
subplot(3,3,7)
plot(time,WG7,'.-b')
subplot(3,3,8)
plot(time,WG8,'.-b')
subplot(3,3,9)
plot(time,WG9,'.-b')
etas = [mean(WG1) mean(WG2) mean(WG3) mean(WG4) mean(WG5) mean(WG6) mean(WG7) mean(WG8) mean(WG9)];
figure,plot(xS,etas,'o-')